version: '3.8'

services:
  api:
    build:
      context: ./CMA-BC
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - postgres
    networks:
      - red-web
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      OCI_NAMESPACE: ${OCI_NAMESPACE}
      OCI_BUCKET_NAME: ${OCI_BUCKET_NAME}
      OCI_REGION: ${OCI_REGION}
    volumes:
      - ./CMA-BC/src:/app/src
      - ~/.oci:/root/.oci:ro

  postgres:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-web
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - red-web
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      # Montamos la carpeta completa del frontend para hot-reloading
      - ./CMA-FT:/app

networks:
  red-web:
    external: true

volumes:
  postgres_data:

